version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:latest
    container_name: firefox
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  opera:
    image: selenium/node-opera:latest
    container_name: opera
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
